### PR TITLE
Code Review for <Space Travelers Hub> React Project

### PR DESCRIPTION
**Pull request by luigirazum**
# Hello Dear Code Reviewers Team 👋,
### The following requirements 📌 were fulfilled this time:

- 🎯 Config and basic setup
    > image
- 🎯 Fetch Data and update store.
    - 📌 This was done for Rockets.
        > image
    - 📌 This was done for Missions
        > image
- 🎯 Render UI lists
    - 📌 Render a list of Rockets
        > image
    - 📌 Render a list of Missions
        > image
- 🎯 Write actions and reducers for booking rockets and joining missions
    - 📌For booking rockets
        >  image
    - 📌For joining missions
        >  image
- 🎯 Write actions and reducers for canceling rockets and leaving missions
    - 📌For canceling a rocket reservation
        >  image
    - 📌For leaving a mission
        >  image
- 🎯 Render UI: conditional components rendering
    - 📌Showing or not the reserved badge, and button for booking or canceling a reservation for rockets.
        >  image
    - 📌Showing NOT A MEMBER or ACTIVE MEMBER of a mission with join or leave mission button for missions.
        >  image
- 🎯 Render UI: My Profile section
    - 📌Render a list of reserved rockets
        >  image
    - 📌Render a list of joined missions
        >  image
- 🎯 Optionals Enhancers
    - 📌Show placeholder text when no reserved rockets nor joined missions.
        >  image
    - 📌Cancel and leave buttons for rockets and missions can be dispatched from my profile.
        >  image
    - 📌Read more button for rockets and missions that open a new browser with wikipedia info.
        >  image
### A working demo right below 👇
   > space-travelers-wikipedia
## ⚠ IMPORTANT NOTE ⚠
I worked "solo" in this project because there is no one else in the same week as I am. Here is the email that Microverse is allowing me to continue the program in "solo".
> image
### Luis 🙋‍♂️

### CODE REVIEW

**Review by elisha2kyakpo1 — CHANGES_REQUESTED** [review]
Hi 👋 @luigirazum, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️ The PR title and description look good and professional.
✔️ No linter errors.
✔️ Descriptive readme file.

## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly add tests for all the components and functions, there is no exceptions for this because you accepted to work solo on a collaborative project. This is a requirement for this project.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by luigirazum** [comment]
Thanks for the feedback, I totally forgot the tests.

**Review by BenMukebo — APPROVED** [review]
<h1>Status: Approve  :champagne:  :+1: :confetti_ball: 

### **Hi @luigirazum**, 

### **Congratulations! 🎉 Project Approved ✅**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 


### To Highlight :1st_place_medal: 
- Your Pull Request has a proper title and description. ✔️  
- Descriptive README file. ✔️  
- Your Design looks awesome, keep rocking :rocket: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers :clinking_glasses:  and Happy coding!!! :dancers:💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by luigirazum** [comment]
Thanks a lot @BenMukebo

**Pull request merged**
